### ISSUE TITLE
What is the property `date` used for?

### ISSUE THREAD

**Issue by StephanMeijer** [wordproof/timestamp-standard#8]
I see a lot of properties called `date`. What is this date? The date of publishing the object, the data of creation of the object or the date of hashing? How can we tackle any manipulation of this date?

**Comment by marijnbent** [comment]
This is when the last change happened to the object in the database, as you can timestamp older objects as well. The date of the timestamp itself is only saved in the blockchain. I do think we can clarify the property to https://schema.org/dateModified
